### ISSUE TITLE
Question : Binary Outcome?

### ISSUE THREAD

**Issue by BrianMiner** [MCKnaus/dmlmt#1]
Quick question, can we use the double machine learning method with a binary outcome variable?

**Comment by MCKnaus** [comment]
Yes it is possible. However, it might change the choice of the machine learner you use to predict the outcome component of DML. I uploaded a new version of dmlmt that allows to specify the outcome family as binomial for binary outcomes. Then logistic Lasso is used for prediction of the outcome. If you want to use something else, check the last section of the readme.

**Comment by BrianMiner** [comment]
Thanks, is the process the exact same from the original paper just using the proper learner and calculating residuals as 1 or 0 minus the probability from the model?

**Comment by MCKnaus** [comment]
Exactly. Only the learner changes.

**Comment by BrianMiner** [comment]
I assume that the theoretical guarantees become approximate outside of a normally distributed error though right?

**Comment by MCKnaus** [comment]
You have indeed to assume that the logistic prediction model provides an accurate approximation to the conditional probability of the outcome. If you are not willing to make this assumption, you can use something more flexible, e.g., random forest as described in the readme.

**Comment by Aminshnn** [comment]
I am wondering if the theory of "Orthogonalization" is only valid for regression with continuous treatment and continuous outcome? Is there any theory that we can use this approach when the outcome is binary?
Based on your comment, we just need to replace the regression models with classification ones. Am I right? So, if the outcome is binary and the treatment is continuous, we use regression for the treatment and classification for the outcome? 
Thanks

**Comment by MCKnaus** [comment]
For binary outcome you are right. However, regarding continuous treatment, it is more complicated than that. See https://arxiv.org/abs/2004.03036
